apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tasks.orderlytask.k8s.io
spec:
  group: orderlytask.k8s.io
  version: v1alpha1
  names:
    kind: Task
    plural: tasks
  scope: Namespaced
  additionalPrinterColumns:
  - name: Order
    type: integer
    description: task order
    JSONPath: .spec.order
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Complete
    type: string
    JSONPath: .status.complete
