apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tasks.orderly-task.k8s.io
spec:
  group: orderly-task.k8s.io
  version: v1alpha1
  names:
    kind: Task
    plural: tasks
  scope: Namespaced
