apiVersion: orderlytask.k8s.io/v1alpha1
kind: Task
metadata:
  name: example-task7
spec:
  jobSpec:
    parallelism: 1
    template:
      metadata:
        name: myjob
      spec:
        containers:
          - name: hello
            image: busybox:1.33.1
            command: [ "sleep", "120" ]
        restartPolicy: OnFailure
  order: 10
